name: my_project
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  image_picker: ^1.1.1
  dio: ^5.4.3+1
  sqflite: ^2.3.3+1
  image: ^4.1.7
  cached_network_image: ^3.3.1
  fan_carousel_image_slider: ^0.1.2
  path: ^1.9.0
  shared_preferences: ^2.2.3

  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lang/

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/ecommerce-checkout-logo-white-grey-background_162944-7227.jpg"
  image_path_ios: "assets/ecommerce-checkout-logo-white-grey-background_162944-7227.jpg"
  adaptive_icon_background: "assets/playstore.png"
  adaptive_icon_foreground: "assets/playstore.png"

  # Uncomment and add the images if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
